### ISSUE TITLE
The driver does not compile with Debian Sid kernel 6.11.2

### ISSUE THREAD

**Issue by Makhno77** [Fred78290/nct6687d#102]
As per the title, the driver does not compile: I attach the make.log
Regards
[6687.log](https://github.com/user-attachments/files/17284774/6687.log)

**Comment by Fred78290** [comment]
Get latest version and rebuild the dkms package. It was fixed last month

**Comment by Makhno77** [comment]
Thanks for the reply but the error seems the same
[6687b.log](https://github.com/user-attachments/files/17292119/6687b.log)

**Comment by Makhno77** [comment]
In data martedì 8 ottobre 2024 15:21:51 CEST, xaizek ha scritto:
> You didn't update the sources or didn't run `make dkms/install`

You're right, the second time I just ran make install, too much haste. 
Sorry for the noise.
Cheers

-- 
Marco Valli

**Comment by Fred78290** [comment]
@xaizek Thanks
