### ISSUE TITLE
CPU Vcore: inconsistent label and decimal places

### ISSUE THREAD

**Issue by graysky2** [Fred78290/nct6687d#11]
Is it possible have the value for `CPU Vcore` to get reported out in volts with three decimals?  Currently, it reads out in mV with two decimals when under 1 volt but changes to volts with two decimals when >1 volt.  Makes logging the output difficult with mixed units.

Example:
```
CPU Vcore:       1.23 V  (min =  +0.22 V, max =  +1.41 V)
```
and
```
CPU Vcore:     266.00 mV (min =  +0.22 V, max =  +1.41 V)
```

**Comment by Fred78290** [comment]
The module is not responsible of the display. all values reported by the module are integer

If you want more decimals, you must configure the displayer.

```
man sensors
```
