### ISSUE TITLE
Exec Format Error on Fedora 35

### ISSUE THREAD

**Issue by Mossy93** [Fred78290/nct6687d#14]
Hello,

I noticed my fan speeds and voltages were not working recently. Now when I attempt to do `sudo modprobe nct6687` I get `modprobe: ERROR: could not insert 'nct6687': Exec format error`.

I tried to do `make install` again, but no luck.

**Comment by Fred78290** [comment]
Hello,

Try make clean install.

Regards

**Comment by Mossy93** [comment]
> Hello,
> 
> Try make clean install.
> 
> Regards

Gave me
```modprobe: ERROR: could not insert 'nct6687': Exec format error
make: *** [Makefile:9: install] Error 1```

**Comment by Fred78290** [comment]
It's your first install or the error occured after OS upgrade?

It's look like a problem with your   install of GCC.

**Comment by Mossy93** [comment]
This happened after an OS upgrade.

**Comment by Fred78290** [comment]
![image](https://user-images.githubusercontent.com/245759/142011126-11fc9de6-7b79-4e9d-9347-d35723112188.png)

Hello, I have installed a fresh VM with Fedora35 on vmware, so except that the io controller nc6687d is not present i didn't have problem.
I think that you something broken on your distribution.

Not concerning the module itself, i close the issue.

Regards

**Comment by Mossy93** [comment]
I just did a `dnf` package update today and it updated some of the kernel packages. Now it is working again.
