### ISSUE TITLE
Kernel patch

### ISSUE THREAD

**Issue by Semmelrocks** [Fred78290/nct6687d#15]
Hi,

I'd created a Kernel patch for this module. Tested successfully on Kernel version 5.10.76.

[nct6687d.patch.txt](https://github.com/Fred78290/nct6687d/files/7681354/nct6687d.patch.txt)

And here is new version for Kernel-5.15.32-r1

[nct6687d-5.15.32-r1.patch.txt](https://github.com/Fred78290/nct6687d/files/8641371/nct6687d-5.15.32-r1.patch.txt)

**Comment by Fred78290** [comment]
Hi all, thank you for contribution.

Is the patch remove the detection inside nct6683.c?

Regards

**Comment by Semmelrocks** [comment]
I didn't changed anything there. The patch will add nct6687 to the kernel makefile and Kconfig as new option directly under nct6683.

**Comment by Jeoshua** [comment]
I have 6683 blacklisted, both 6683 and this 6687 patch compiled as modules, and 6687 just works.

**Comment by Jeoshua** [comment]
And I made it through the upgrade to 5.16rc4 without issue. It seems this Just Works.

**Comment by helmchenlord** [comment]
I've created a patch for kernel 6.1.12
[nct6687d-6.1.12.patch.txt](https://github.com/Fred78290/nct6687d/files/10750526/nct6687d-6.1.12.patch.txt)
