### ISSUE TITLE
Not all fans are updated

### ISSUE THREAD

**Issue by ykurlaev** [Fred78290/nct6687d#2]
In `nct6687_update_fans` you have `for (i = 0; i < ARRAY_SIZE(data->rpm); i++)`, but size of `data->rpm` is always 3 (`u16 rpm[3][NCT6687_NUM_REG_FAN];`).
Also, maybe it's good idea to add debug print that is already there for temperature and voltage update functions to the fan update function as well?

**Comment by Fred78290** [comment]
Thanks for your report.
I fixed the issue.
