### ISSUE TITLE
DKMS does not work

### ISSUE THREAD

**Issue by Mossy93** [Fred78290/nct6687d#41]
Hello,

I just updated my Kernel on Endeavour OS, however the DKMS install of your module did not work.

[Here is the output of dkms when it updated](https://pastebin.com/NkLdtYTb)
[Here is the Build Log](https://pastebin.com/upiYR9eB)

**Comment by pipes80-collab** [comment]
doesn't work with have you compiled with this method?
~$ git clone https://github.com/Fred78290/nct6687d
~$ cd nct6687d
~$ make dkms/install

**Comment by Mossy93** [comment]
Yes.
Also I cloned just last Monday (May 23rd)
