### ISSUE TITLE
Not compatible wit Kernel 5.11

### ISSUE THREAD

**Issue by DoXer67** [Fred78290/nct6687d#5]
I hope you update the module for Linux 5.11
Thank you.

**Comment by Fred78290** [comment]
Hi,

I'll update when I'll be able to install Linux 5.11 on Ubuntu TLS 20.04-2 without lost NVIDIA modules and running with 800x600 resolution :)

**Comment by berniyh** [comment]
> I hope you update the module for Linux 5.11
> Thank you.

Works for me?
(On 5.11.0)

**Comment by berniyh** [comment]
Maybe the problem was just that the kernel automatically loaded the nct6683 driver and thus the driver listed here fails (because the device is in use)?
In that case all you would have to do is to blacklist the nct6683 module.

**Comment by Fred78290** [comment]
> Maybe the problem was just that the kernel automatically loaded the nct6683 driver and thus the driver listed here fails (because the device is in use)?
> In that case all you would have to do is to blacklist the nct6683 module.

Probably the true reason why it doesn't load, because modules using the same hardware are exclusive by using a lock.

**Comment by TheMangoTrain** [comment]
Just upgrading to kernal 5.11 didn't make any change in sensor output --- my fans still not detected.

Running this github project, now everything works!

Many thanks!

**Comment by pavilalopes** [comment]
Works for me on Ubuntu 21.04 with kernel 5.11.0
