### ISSUE TITLE
Warning after compiling on Debian kernel 6.1.7

### ISSUE THREAD

**Issue by Makhno77** [Fred78290/nct6687d#57]
--snip--
dkms: running auto installation service for kernel 6.1.0-2-amd64:Deprecated feature: REMAKE_INITRD (/var/lib/dkms/nct6687d/1/source/dkms.conf)
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/nct6687d/1/source/dkms.conf)
--snip--
Despite the warning the module works.
Regards

**Comment by Fred78290** [comment]
Thank's for the warn.

**Comment by Makhno77** [comment]
Thank you for your work, Fred.

**Comment by Fred78290** [comment]
I don't have anymore time to switch to the kernel 6.x with official distribution because still unsupported.
