### ISSUE TITLE
Stopped working Fedora Silverblue 37

### ISSUE THREAD

**Issue by tecumses** [Fred78290/nct6687d#62]
Hello,
I had it running for a short time, worked perfectly, but suddenly it is not recognized anymore. I tried everything from rebuilding inside a toolbox, installing the rpms via rpm-ostree, nothing seems to work anymore. 
Board is a MSI Pro b660m-a
Any help is appreciated.
Thanks and regards 

edit: works with terminalcommand

> modprobe nct6687 force=1 

after boot

**Comment by Fred78290** [comment]
Probably you must black list nct6683 module.
