### ISSUE TITLE
Can't compile since kernel update 5.15.0-60 on Mint Cinnamon

### ISSUE THREAD

**Issue by Lowrida** [Fred78290/nct6687d#63]
After every update i could compile again and it always works after that. But since the latest updates i can't compile anymore. 
It gives me this error:

```
modprobe: ERROR: could not insert 'nct6687': Exec format error
```

**Comment by Lowrida** [comment]
Never mind. Cloned it and now it works again! ;)

**Comment by Fred78290** [comment]
Hi, This problem already occured during kernel update on ubuntu. It's not really a problem of the module but a problem of kernel dev environment.

Wait an update of you distribution and it will be fixed.

**Comment by Lowrida** [comment]
It is fixed already! I guess i had an old version.. so cloning and compiling again did the trick!
