### ISSUE TITLE
Need to `make install` after reboot; why

### ISSUE THREAD

**Issue by TheMangoTrain** [Fred78290/nct6687d#7]
Hey

After a reboot, initially `sensors` was showing the old output (no fans detected). After running `make install` on this project again, sensors showing full output.

What does one need to do to make this permanent?

Also, any issue when upgrading Ubuntu or kernel in the future?

**Comment by Fred78290** [comment]
Hello,

Just add nct6687 into /etc/modules
```
sudo sh -c 'echo "nct6687" >> /etc/modules'
```
