### ISSUE TITLE
Can't give fan control back to the firmware

### ISSUE THREAD

**Issue by Atemu** [Fred78290/nct6687d#78]
After setting fan speed manually, there is no obvious way to give fan control back to the motherboard firmware; applying the firmware fan curves again. It'd be great if you could i.e. write `-1` into the pwm device to do that.

**Comment by SergeyMy** [comment]
There is NO way to return, it seems like it should return when unloading the module, but alas, there is no way.

**Comment by Fred78290** [comment]
Hi all, the main problem is to collect original settings, save it and restore it as needed.

In bios you can set different level for speed fan according temperature. Via the NCT6667 register you just say run the fan as this speed, so with fancontrol when you ask to save the state, it will be the instant state not the settings from bios.

I think that the temperature/fan speed according the temperature that you set in the bios is not handled by NCT itself but with another helper controller.

Having reading NCT 6683 technical book, I haven't see the feature fan speed/temperature control.

In the official kernel the feature to change fan speed is not available.

Help welcome.

**Comment by SergeyMy** [comment]
I just started looking yesterday... in kernel 6.5.8 :) such drivers have a control mode register manually or automatically....
I'll continue searching :)

**Comment by SergeyMy** [comment]
> Help welcome.

static void nct6687_restore_fan_control
{
.....
nct6687_write(data, NCT6687_REG_FAN_CTRL_MODE(0), 0);
} //end static void nct6687_restore_fan_control :):):)
FAN_CTRL_MODE 
1 - manual
0 -auto

**Comment by Fred78290** [comment]
Create another template group command allowing switch mode auto/manual for pwm

`
SENSOR_TEMPLATE(pwmode, "pwmmode%d", S_IRUGO, show_pw, switch_pwm, 0);
`
Why not

**Comment by SergeyMy** [comment]
better by analogy with // adhere to the standard ;)
**Documentation/hwmon/nct6775.rst**
```
sysfs attributes
----------------

pwm[1-7]
    - this file stores PWM duty cycle or DC value (fan speed) in range:

           0 (lowest speed) to 255 (full)

pwm[1-7]_enable
    - this file controls mode of fan/temperature control:

        * 0 Fan control disabled (fans set to maximum speed)
        * 1 Manual mode, write to pwm[0-5] any value 0-255
        * 2 "Thermal Cruise" mode
        * 3 "Fan Speed Cruise" mode
        * 4 "Smart Fan III" mode (NCT6775F only)
        * 5 "Smart Fan IV" mode

pwm[1-7]_mode
    - controls if output is PWM or DC level

        * 0 DC output
        * 1 PWM output

```

PS pwm[1-7]_mode **DC/PWM**  is also in nct6687, all that remains is to find it....
PSPS where did you find out about NCT6687_REG_FAN_CTRL_MODE 0xA00 can you share the source/datasheet? but on NCT6683?

**Comment by SergeyMy** [comment]
@Fred78290 
ничего не понимаю :( судя по коду nct6687_write(data, NCT6687_REG_FAN_CTRL_MODE(0), 0); излишне т.к. регистр сохранялся и должен был восстанавливатся, но этого не происходило.
сей час же все работает как задуманно. :(
посмотрел исходный код в ядре 6.6-rc7 там полный ужас.
So I’m thinking what to take as a basis? yours or... https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/?h=v6.6-rc7  or both :)

**Comment by SergeyMy** [comment]
@Fred78290 
do you have a **register map nct6687** because it takes a long time to search through reverse engineering :(

**Comment by Fred78290** [comment]
I have the same and my 5700G die, waiting for RAM.
.

**Comment by SergeyMy** [comment]
NCT6687_REG_PWM_SOURCE_TEMP_VALUE(x) (0xca0 + (x))
:)

**Comment by SergeyMy** [comment]
> I have the same and my 5700G die, **waiting for RAM**. .

I took an unnamed 2 to 16 from a Chinese supplier, happy as an elephant
![изображение](https://github.com/Fred78290/nct6687d/assets/131688106/b5ec2778-3754-4059-8198-4615bddf86e4)
